workspace:
  base: /test
  path: ssk

services:
  web:
    image: fpfis/php56-dev
    environment:
     - DOCUMENT_ROOT=/test/ssk
  mysql:
    image: fpfis/mysql56
  selenium:
    image: selenium/standalone-chrome
#  solr:
#    image: fpfis/solr5

pipeline:

  prepare-mysql:
    group: prepare
    image: fpfis/mysql56
    commands:
      - sleep 5
      - mysqladmin -h mysql -uroot create database

  prepare-php:
    group: prepare
    image: fpfis/php56-dev
    commands:
      - php --version
      - composer install

  build-dev:
    image: fpfis/php56-dev
    commands:
      - ./bin/phing build-dev -D behat.base_url='http://web:8080' -D'behat.wd_host'='http://selenium:4444/wd/hub' -D'behat.browser_name'='chrome' -D'composer.bin'=$(which composer)
  install:
    image: fpfis/php56-dev
    commands:
      - ./bin/phing install-dev -D'drupal.db.host'='mysql' -D'drupal.db.name'=database

  test:
    image: fpfis/php56-dev
    commands:
      - ./bin/phing behat

  build-dist:
    image: fpfis/php56-dev
    commands:
      - ./bin/phing build-dist -D'composer.bin'=$(which composer)
      - tar -czf ${DRONE_REPO_NAME}-${DRONE_TAG}.tar.gz -C build .
    when:
      event: tag

  github_release:
    image: plugins/github-release
    files:
      - ${DRONE_REPO_NAME}-${DRONE_TAG}.tar.gz
    checksum:
      - sha1
      - sha256
      - sha512
    secrets: [ GITHUB_RELEASE_API_KEY ]
    when:
      event: tag
